In [1]:
d = {'one': 1, 'two': 2, 'three': 3}

In [3]:
d.setdefault('one')

1

In [4]:
d.setdefault('four')

In [5]:
d

{'one': 1, 'two': 2, 'three': 3, 'four': None}

In [7]:
d.setdefault('four',4)

In [8]:
d

{'one': 1, 'two': 2, 'three': 3, 'four': None}

In [9]:
d.setdefault('five', 5)

5

In [10]:
d

{'one': 1, 'two': 2, 'three': 3, 'four': None, 'five': 5}

In [11]:
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [12]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [13]:
print(np.__version__)

1.18.1


In [14]:
print(type(arr))

<class 'numpy.ndarray'>


In [15]:
arr = np.array([[1, 2, 3], [4, 5, 6]])


In [16]:
arr.ndim

2

In [17]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
arr.ndim

3

In [18]:
arr = np.array([1, 2, 3, 4], ndmin=5)


In [19]:
arr

array([[[[[1, 2, 3, 4]]]]])

In [20]:
arr

array([[[[[1, 2, 3, 4]]]]])

In [21]:
print(arr)

[[[[[1 2 3 4]]]]]


In [22]:
arr.ndim

5

In [23]:
arr = np.array([[1, 2, 3], [4, 5, 6]])


In [24]:
arr[0,1]

2

In [25]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


In [27]:
arr[0,0,-1]

3

In [28]:
arr[1:4]

array([[[ 7,  8,  9],
        [10, 11, 12]]])

In [29]:
arr.shape

(2, 2, 3)

In [30]:
arr.size

12

In [33]:
len(arr)

2

In [34]:
arr.ndim

3

In [35]:
arr.dtype

dtype('int64')

In [36]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])


In [37]:
arr[:4]

array([1, 2, 3, 4])

In [38]:
arr[-3:-1]

array([5, 6])

In [39]:
arr[1:5:2]

array([2, 4])

In [40]:
arr[::2]

array([1, 3, 5, 7])

In [41]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])


In [42]:
arr[0:2,2]

array([3, 8])