# The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations.

## General Broadcasting RUles

## Indexing

# All arrays generated by basic slicing are always views of the original array.

In [2]:
import numpy as np
x = np.arange(12)

In [3]:
x[1:7:2]

array([1, 3, 5])

In [7]:
x[-5:-1]

array([ 7,  8,  9, 10])

### ellipsis

In [8]:
x[5:]

array([ 5,  6,  7,  8,  9, 10, 11])

In [9]:
x = x.reshape(3,4)

In [10]:
x[1:]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
x[1]

array([4, 5, 6, 7])

In [13]:
x[1:2]

array([[4, 5, 6, 7]])