# Array creation¶


In [2]:
import numpy as np
np.array([1,1,1,])

array([1, 1, 1])

In [4]:
np.array(tuple((1,2,3,4)))

array([1, 2, 3, 4])

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.eye((4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
np.eye((3,4))

TypeError: 'tuple' object cannot be interpreted as an integer

In [12]:
np.linspace(3,5,5) # starting, endpoint and number of elements guarenteed using np.linspace()

array([3. , 3.5, 4. , 4.5, 5. ])

In [14]:
np.arange(1,10,3) # starting and difference guarented not endpoint and number

array([1, 4, 7])

In [17]:
np.indices((1,))

array([[0]])

In [18]:
np.indices((1,1,))

array([[[0]],

       [[0]]])

In [20]:
a = np.indices((2,2))

In [21]:
a.shape

(2, 2, 2)

In [22]:
a

array([[[0, 0],
        [1, 1]],

       [[0, 1],
        [0, 1]]])

In [23]:
np.indices((3,))

array([[0, 1, 2]])

In [24]:
np.indices((3,1))

array([[[0],
        [1],
        [2]],

       [[0],
        [0],
        [0]]])

# Working with IO

## Importing data with genfromtxt

In [26]:
import numpy as np
from io import StringIO

In [27]:
data = u"1, 2, 3, 4\n5, 6, 7, 8"

In [28]:
type(data)

str

In [29]:
repr(data)

"'1, 2, 3, 4\\n5, 6, 7, 8'"

In [30]:
np.genfromtxt(StringIO(data), delimiter=',')

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

###### The delimiter keyword is used to define how the splitting should take place

In [35]:
np.genfromtxt(StringIO('datas/csvtorandomize.csv'), delimiter=',')

array(nan)

In [35]:
np.genfromtxt(StringIO('datas/csvtorandomize.csv'), delimiter=',')

array(nan)

In [42]:
np.genfromtxt(StringIO('datas/csv_to_randomize.csv'), delimiter=None)

array(nan)

In [34]:
ls datas/

class11datacollection.csv      Class11DataCollection.xlsx  csvtorandomize.csv
class11datacollection.csv.csv  csv_to_randomize.csv        gopalsanclean.csv


In [43]:
data = u"  1  2  3\n  4  5 67\n890123  4"

In [44]:
np.genfromtxt(StringIO(data), delimiter=3)

array([[  1.,   2.,   3.],
       [  4.,   5.,  67.],
       [890., 123.,   4.]])

In [54]:
data = u"  1  2  3\n  4  5 67\n890123  4"


In [55]:

np.genfromtxt(StringIO(data), delimiter=3)

array([[  1.,   2.,   3.],
       [  4.,   5.,  67.],
       [890., 123.,   4.]])

In [74]:
data = u"123456789\n   4  7 9\n   4567999"

In [75]:
np.genfromtxt(StringIO(data), delimiter=(4, 3, 2))

array([[1234.,  567.,   89.],
       [   4.,    7.,    9.],
       [   4.,  567.,   99.]])

In [1]:
import numpy as np

In [9]:

np.genfromtxt('datas/csv_to_randomize.csv')

ValueError: Some errors were detected !
    Line #2 (got 12 columns instead of 6)
    Line #3 (got 11 columns instead of 6)
    Line #4 (got 19 columns instead of 6)
    Line #5 (got 22 columns instead of 6)
    Line #6 (got 14 columns instead of 6)
    Line #7 (got 12 columns instead of 6)
    Line #8 (got 11 columns instead of 6)
    Line #9 (got 13 columns instead of 6)
    Line #10 (got 18 columns instead of 6)
    Line #11 (got 14 columns instead of 6)
    Line #12 (got 17 columns instead of 6)
    Line #13 (got 5 columns instead of 6)
    Line #14 (got 10 columns instead of 6)
    Line #15 (got 12 columns instead of 6)
    Line #16 (got 24 columns instead of 6)
    Line #17 (got 9 columns instead of 6)
    Line #18 (got 7 columns instead of 6)
    Line #19 (got 7 columns instead of 6)
    Line #20 (got 15 columns instead of 6)
    Line #21 (got 16 columns instead of 6)
    Line #22 (got 13 columns instead of 6)
    Line #23 (got 14 columns instead of 6)
    Line #24 (got 12 columns instead of 6)
    Line #25 (got 17 columns instead of 6)
    Line #26 (got 12 columns instead of 6)
    Line #27 (got 11 columns instead of 6)
    Line #28 (got 17 columns instead of 6)
    Line #29 (got 30 columns instead of 6)
    Line #30 (got 11 columns instead of 6)
    Line #31 (got 16 columns instead of 6)
    Line #32 (got 18 columns instead of 6)
    Line #33 (got 11 columns instead of 6)
    Line #34 (got 9 columns instead of 6)
    Line #35 (got 15 columns instead of 6)
    Line #36 (got 18 columns instead of 6)
    Line #37 (got 9 columns instead of 6)
    Line #38 (got 14 columns instead of 6)
    Line #39 (got 10 columns instead of 6)
    Line #40 (got 11 columns instead of 6)
    Line #41 (got 9 columns instead of 6)
    Line #42 (got 10 columns instead of 6)
    Line #43 (got 17 columns instead of 6)
    Line #44 (got 19 columns instead of 6)
    Line #45 (got 10 columns instead of 6)
    Line #46 (got 11 columns instead of 6)
    Line #47 (got 11 columns instead of 6)
    Line #48 (got 17 columns instead of 6)
    Line #49 (got 8 columns instead of 6)
    Line #50 (got 14 columns instead of 6)
    Line #51 (got 17 columns instead of 6)
    Line #52 (got 13 columns instead of 6)
    Line #53 (got 4 columns instead of 6)
    Line #54 (got 28 columns instead of 6)
    Line #55 (got 5 columns instead of 6)
    Line #56 (got 11 columns instead of 6)
    Line #57 (got 26 columns instead of 6)
    Line #58 (got 27 columns instead of 6)
    Line #59 (got 16 columns instead of 6)
    Line #60 (got 10 columns instead of 6)
    Line #61 (got 13 columns instead of 6)
    Line #62 (got 8 columns instead of 6)
    Line #63 (got 14 columns instead of 6)
    Line #64 (got 9 columns instead of 6)
    Line #65 (got 12 columns instead of 6)
    Line #66 (got 9 columns instead of 6)
    Line #67 (got 15 columns instead of 6)
    Line #68 (got 10 columns instead of 6)
    Line #69 (got 10 columns instead of 6)
    Line #70 (got 12 columns instead of 6)
    Line #71 (got 10 columns instead of 6)
    Line #72 (got 17 columns instead of 6)
    Line #73 (got 14 columns instead of 6)
    Line #74 (got 18 columns instead of 6)
    Line #75 (got 20 columns instead of 6)
    Line #76 (got 12 columns instead of 6)
    Line #77 (got 13 columns instead of 6)
    Line #78 (got 13 columns instead of 6)
    Line #79 (got 15 columns instead of 6)
    Line #80 (got 7 columns instead of 6)
    Line #81 (got 12 columns instead of 6)
    Line #82 (got 16 columns instead of 6)
    Line #83 (got 9 columns instead of 6)
    Line #84 (got 14 columns instead of 6)
    Line #85 (got 10 columns instead of 6)
    Line #86 (got 14 columns instead of 6)
    Line #87 (got 11 columns instead of 6)
    Line #88 (got 12 columns instead of 6)
    Line #89 (got 24 columns instead of 6)
    Line #90 (got 21 columns instead of 6)
    Line #91 (got 10 columns instead of 6)
    Line #92 (got 13 columns instead of 6)
    Line #93 (got 23 columns instead of 6)
    Line #94 (got 18 columns instead of 6)
    Line #95 (got 7 columns instead of 6)
    Line #96 (got 24 columns instead of 6)
    Line #97 (got 10 columns instead of 6)
    Line #98 (got 17 columns instead of 6)
    Line #99 (got 28 columns instead of 6)
    Line #100 (got 22 columns instead of 6)
    Line #101 (got 18 columns instead of 6)
    Line #102 (got 17 columns instead of 6)
    Line #103 (got 15 columns instead of 6)
    Line #104 (got 10 columns instead of 6)
    Line #105 (got 11 columns instead of 6)
    Line #106 (got 11 columns instead of 6)
    Line #107 (got 13 columns instead of 6)
    Line #108 (got 8 columns instead of 6)
    Line #109 (got 23 columns instead of 6)
    Line #110 (got 13 columns instead of 6)
    Line #111 (got 14 columns instead of 6)
    Line #112 (got 17 columns instead of 6)
    Line #113 (got 20 columns instead of 6)
    Line #114 (got 20 columns instead of 6)
    Line #115 (got 11 columns instead of 6)
    Line #116 (got 17 columns instead of 6)
    Line #117 (got 12 columns instead of 6)
    Line #118 (got 16 columns instead of 6)
    Line #119 (got 14 columns instead of 6)
    Line #120 (got 13 columns instead of 6)
    Line #121 (got 12 columns instead of 6)
    Line #122 (got 12 columns instead of 6)
    Line #123 (got 11 columns instead of 6)
    Line #124 (got 11 columns instead of 6)
    Line #125 (got 13 columns instead of 6)
    Line #126 (got 16 columns instead of 6)
    Line #127 (got 16 columns instead of 6)
    Line #128 (got 17 columns instead of 6)
    Line #129 (got 15 columns instead of 6)
    Line #130 (got 10 columns instead of 6)
    Line #131 (got 10 columns instead of 6)
    Line #132 (got 21 columns instead of 6)
    Line #133 (got 10 columns instead of 6)
    Line #135 (got 10 columns instead of 6)
    Line #136 (got 16 columns instead of 6)
    Line #137 (got 13 columns instead of 6)
    Line #138 (got 17 columns instead of 6)
    Line #139 (got 13 columns instead of 6)
    Line #140 (got 38 columns instead of 6)
    Line #141 (got 9 columns instead of 6)
    Line #142 (got 7 columns instead of 6)
    Line #143 (got 9 columns instead of 6)
    Line #144 (got 11 columns instead of 6)
    Line #145 (got 8 columns instead of 6)
    Line #146 (got 13 columns instead of 6)
    Line #147 (got 21 columns instead of 6)
    Line #148 (got 8 columns instead of 6)
    Line #149 (got 9 columns instead of 6)
    Line #150 (got 18 columns instead of 6)
    Line #151 (got 13 columns instead of 6)
    Line #152 (got 13 columns instead of 6)
    Line #153 (got 4 columns instead of 6)
    Line #154 (got 12 columns instead of 6)
    Line #155 (got 10 columns instead of 6)
    Line #156 (got 12 columns instead of 6)
    Line #157 (got 17 columns instead of 6)
    Line #158 (got 16 columns instead of 6)
    Line #159 (got 16 columns instead of 6)
    Line #160 (got 8 columns instead of 6)
    Line #161 (got 14 columns instead of 6)
    Line #162 (got 14 columns instead of 6)
    Line #163 (got 35 columns instead of 6)
    Line #164 (got 38 columns instead of 6)
    Line #165 (got 24 columns instead of 6)
    Line #166 (got 26 columns instead of 6)
    Line #167 (got 21 columns instead of 6)
    Line #168 (got 35 columns instead of 6)
    Line #169 (got 26 columns instead of 6)
    Line #170 (got 15 columns instead of 6)
    Line #172 (got 27 columns instead of 6)
    Line #173 (got 22 columns instead of 6)
    Line #174 (got 25 columns instead of 6)
    Line #175 (got 24 columns instead of 6)
    Line #176 (got 32 columns instead of 6)
    Line #177 (got 24 columns instead of 6)
    Line #178 (got 33 columns instead of 6)
    Line #179 (got 26 columns instead of 6)
    Line #180 (got 16 columns instead of 6)
    Line #181 (got 19 columns instead of 6)
    Line #182 (got 9 columns instead of 6)
    Line #183 (got 10 columns instead of 6)
    Line #184 (got 23 columns instead of 6)
    Line #185 (got 13 columns instead of 6)
    Line #186 (got 10 columns instead of 6)
    Line #187 (got 11 columns instead of 6)
    Line #188 (got 12 columns instead of 6)
    Line #189 (got 23 columns instead of 6)
    Line #190 (got 21 columns instead of 6)
    Line #191 (got 16 columns instead of 6)
    Line #192 (got 17 columns instead of 6)
    Line #193 (got 17 columns instead of 6)
    Line #194 (got 8 columns instead of 6)
    Line #196 (got 11 columns instead of 6)
    Line #197 (got 11 columns instead of 6)
    Line #198 (got 9 columns instead of 6)
    Line #199 (got 14 columns instead of 6)
    Line #200 (got 17 columns instead of 6)
    Line #201 (got 11 columns instead of 6)
    Line #202 (got 11 columns instead of 6)
    Line #203 (got 12 columns instead of 6)
    Line #204 (got 14 columns instead of 6)
    Line #205 (got 19 columns instead of 6)
    Line #206 (got 14 columns instead of 6)
    Line #207 (got 23 columns instead of 6)
    Line #209 (got 20 columns instead of 6)
    Line #210 (got 19 columns instead of 6)
    Line #211 (got 16 columns instead of 6)
    Line #212 (got 16 columns instead of 6)
    Line #213 (got 12 columns instead of 6)
    Line #214 (got 16 columns instead of 6)
    Line #215 (got 8 columns instead of 6)
    Line #216 (got 11 columns instead of 6)
    Line #217 (got 13 columns instead of 6)
    Line #218 (got 17 columns instead of 6)
    Line #219 (got 10 columns instead of 6)
    Line #220 (got 10 columns instead of 6)
    Line #221 (got 8 columns instead of 6)
    Line #222 (got 14 columns instead of 6)
    Line #223 (got 7 columns instead of 6)
    Line #224 (got 13 columns instead of 6)
    Line #225 (got 15 columns instead of 6)
    Line #226 (got 17 columns instead of 6)
    Line #227 (got 23 columns instead of 6)
    Line #228 (got 21 columns instead of 6)
    Line #229 (got 13 columns instead of 6)
    Line #230 (got 25 columns instead of 6)
    Line #231 (got 15 columns instead of 6)
    Line #232 (got 16 columns instead of 6)
    Line #233 (got 15 columns instead of 6)
    Line #234 (got 27 columns instead of 6)
    Line #235 (got 7 columns instead of 6)
    Line #236 (got 9 columns instead of 6)
    Line #237 (got 16 columns instead of 6)
    Line #238 (got 11 columns instead of 6)
    Line #239 (got 16 columns instead of 6)
    Line #240 (got 8 columns instead of 6)
    Line #241 (got 18 columns instead of 6)
    Line #242 (got 13 columns instead of 6)
    Line #243 (got 14 columns instead of 6)
    Line #244 (got 13 columns instead of 6)
    Line #245 (got 13 columns instead of 6)
    Line #246 (got 10 columns instead of 6)
    Line #247 (got 8 columns instead of 6)
    Line #248 (got 13 columns instead of 6)
    Line #249 (got 27 columns instead of 6)
    Line #250 (got 26 columns instead of 6)
    Line #251 (got 9 columns instead of 6)
    Line #252 (got 13 columns instead of 6)
    Line #253 (got 19 columns instead of 6)
    Line #254 (got 10 columns instead of 6)
    Line #255 (got 12 columns instead of 6)
    Line #256 (got 11 columns instead of 6)
    Line #257 (got 11 columns instead of 6)
    Line #258 (got 13 columns instead of 6)
    Line #259 (got 8 columns instead of 6)
    Line #260 (got 12 columns instead of 6)
    Line #261 (got 16 columns instead of 6)
    Line #262 (got 14 columns instead of 6)
    Line #263 (got 12 columns instead of 6)
    Line #264 (got 9 columns instead of 6)
    Line #265 (got 28 columns instead of 6)
    Line #266 (got 13 columns instead of 6)
    Line #267 (got 16 columns instead of 6)
    Line #268 (got 9 columns instead of 6)

In [10]:
data = u" 12345\n67 90\n1111 11  "

In [11]:
from io import StringIO

In [14]:
np.genfromtxt(StringIO(data), delimiter=(2,2,3))

array([[ 1., 23., 45.],
       [67.,  9.,  0.],
       [11., 11., 11.]])

### autostrip argument

In [15]:
data = u" 12345\n67 90\n1111 11  "

In [18]:
np.genfromtxt(StringIO(data), delimiter=(2,2,3), autostrip=True)

array([[ 1., 23., 45.],
       [67.,  9.,  0.],
       [11., 11., 11.]])

In [19]:
data = u"hey, jude, dont\nlet, me, down\n sing, a , sadsong"

In [20]:

np.genfromtxt(StringIO(data), delimiter=',')

array([[nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan]])

In [21]:

np.genfromtxt(StringIO(data), delimiter=',', dtype="|U5")

array([['hey', ' jude', ' dont'],
       ['let', ' me', ' down'],
       ['sing', ' a ', ' sads']], dtype='<U5')

In [22]:

np.genfromtxt(StringIO(data), delimiter=',', dtype="|U5", autostrip=True)

array([['hey', 'jude', 'dont'],
       ['let', 'me', 'down'],
       ['sing', 'a', 'sadso']], dtype='<U5')

In [26]:
data = u"1, 2,3   \n4, 5,   6"

In [27]:
np.genfromtxt(StringIO(data), delimiter=',')

array([[1., 2., 3.],
       [4., 5., 6.]])

In [31]:
data  = u"""
# comment of the daata, skip the comment
# this data consists of numeric values, they donot require autostrip
1,3,4
4,5,     6
7,3,1 # last line

"""

In [32]:
np.genfromtxt(StringIO(data), delimiter=',')

array([[1., 3., 4.],
       [4., 5., 6.],
       [7., 3., 1.]])

In [35]:
data = u"""
$this is comment
$ the default comments value is $
$ we change that value using comments argument

1, 4, 6 $ just some value
4.5,   2, 32

"""

In [36]:
np.genfromtxt(StringIO(data), delimiter=',', comments='$')

array([[ 1. ,  4. ,  6. ],
       [ 4.5,  2. , 32. ]])

In [37]:
data = u"""
col1, col2, col3
1,3,4
4,5,6
24.,6,7 # last line

"""

In [38]:
np.genfromtxt(StringIO(data), delimiter=',', names=True)

array([( 1., 3., 4.), ( 4., 5., 6.), (24., 6., 7.)],
      dtype=[('col1', '<f8'), ('col2', '<f8'), ('col3', '<f8')])

In [39]:
data = u"""
# initial lizing
col1, col2, col3
1,3,4
4,5,6
24.,6,7 # last line

"""


In [40]:
np.genfromtxt(StringIO(data), delimiter=',', names=True)

ValueError: Some errors were detected !
    Line #2 (got 3 columns instead of 1)
    Line #3 (got 3 columns instead of 1)
    Line #4 (got 3 columns instead of 1)
    Line #5 (got 3 columns instead of 1)

In [41]:
data = u"""
# initial lizing, values, data
col1, col2, col3
1,3,4
4,5,6
24.,6,7 # last line

"""


In [42]:
np.genfromtxt(StringIO(data), delimiter=',', names=True)

array([(nan, nan, nan), ( 1.,  3.,  4.), ( 4.,  5.,  6.), (24.,  6.,  7.)],
      dtype=[('initial_lizing', '<f8'), ('values', '<f8'), ('data', '<f8')])

## if the optional argument names=True, the first commented line will be examined for names.

### Skipping lines and choosing columns
The skip_header and skip_footer arguments

In [43]:
data = u"""
# this is comment
id, age, salary
1,21,23433
2,32,44444
3,44,488888
4,2,44
5,6,77

"""

In [45]:

np.genfromtxt(StringIO(data), delimiter=',')

array([[        nan,         nan,         nan],
       [1.00000e+00, 2.10000e+01, 2.34330e+04],
       [2.00000e+00, 3.20000e+01, 4.44440e+04],
       [3.00000e+00, 4.40000e+01, 4.88888e+05],
       [4.00000e+00, 2.00000e+00, 4.40000e+01],
       [5.00000e+00, 6.00000e+00, 7.70000e+01]])

In [46]:
np.genfromtxt(StringIO(data), delimiter=',', skip_header=1)

array([[        nan,         nan,         nan],
       [1.00000e+00, 2.10000e+01, 2.34330e+04],
       [2.00000e+00, 3.20000e+01, 4.44440e+04],
       [3.00000e+00, 4.40000e+01, 4.88888e+05],
       [4.00000e+00, 2.00000e+00, 4.40000e+01],
       [5.00000e+00, 6.00000e+00, 7.70000e+01]])

In [48]:
np.genfromtxt(StringIO(data), delimiter=',', skip_header=3)

array([[1.00000e+00, 2.10000e+01, 2.34330e+04],
       [2.00000e+00, 3.20000e+01, 4.44440e+04],
       [3.00000e+00, 4.40000e+01, 4.88888e+05],
       [4.00000e+00, 2.00000e+00, 4.40000e+01],
       [5.00000e+00, 6.00000e+00, 7.70000e+01]])

In [49]:
np.genfromtxt(StringIO(data), skip_footer=1, skip_header=3, delimiter=',', comments='#', autostrip=True)

array([[1.00000e+00, 2.10000e+01, 2.34330e+04],
       [2.00000e+00, 3.20000e+01, 4.44440e+04],
       [3.00000e+00, 4.40000e+01, 4.88888e+05],
       [4.00000e+00, 2.00000e+00, 4.40000e+01]])

### The usecols argument

In [50]:
data = u"1,2,3,4,5\n2,3,4,5,6\n4,4,4,4,4"

In [53]:

np.genfromtxt(StringIO(data), delimiter=',')

array([[1., 2., 3., 4., 5.],
       [2., 3., 4., 5., 6.],
       [4., 4., 4., 4., 4.]])

In [54]:
np.genfromtxt(StringIO(data), delimiter=',', usecols=(0,1))

array([[1., 2.],
       [2., 3.],
       [4., 4.]])

In [57]:
np.genfromtxt(StringIO(data), delimiter=',', usecols=(0,1, -1, -2, 0))

array([[1., 2., 5., 4., 1.],
       [2., 3., 6., 5., 2.],
       [4., 4., 4., 4., 4.]])

In [58]:
data = u"1,2,3,4,5\n2,3,4,5,6\n4,4,4,4,4"

In [59]:
np.genfromtxt(StringIO(data), delimiter=',', names="a,b,c,d,e")

array([(1., 2., 3., 4., 5.), (2., 3., 4., 5., 6.), (4., 4., 4., 4., 4.)],
      dtype=[('a', '<f8'), ('b', '<f8'), ('c', '<f8'), ('d', '<f8'), ('e', '<f8')])

In [60]:
np.genfromtxt(StringIO(data), delimiter=',', names="a,b,c,d,e", usecols='a')


array([(1.,), (2.,), (4.,)], dtype=[('a', '<f8')])

In [61]:
np.genfromtxt(StringIO(data), delimiter=',', names="a,b,c,d,e", usecols=('a', 'd'))

array([(1., 4.), (2., 5.), (4., 4.)], dtype=[('a', '<f8'), ('d', '<f8')])

In [62]:
np.genfromtxt(StringIO(data), delimiter=',', names="a,b,c,d,e", usecols='a', 'd')

SyntaxError: positional argument follows keyword argument (<ipython-input-62-9e75163f348f>, line 1)

## Choosing the data type¶

In [77]:
data = u"1, 2, 3 \n 4 ,5 ,6 "

In [68]:

np.genfromtxt(StringIO(data), names="'a','b','c'", delimiter=',')

array([(1., 2., 3.), (4., 5., 6.)],
      dtype=[('a', '<f8'), ('b', '<f8'), ('c', '<f8')])

In [73]:
np.genfromtxt(StringIO(data), dtype=('a', int))

array([b'1,2,3', b'4,5,6'], dtype='|S8')

In [79]:
np.genfromtxt(data, dtype=[(_, int) for _ in "abc"], delimiter=None)

OSError: 1, 2, 3 
 4 ,5 ,6  not found.

In [80]:
data = StringIO("1 2 3\n 4 5 6")

In [81]:
np.genfromtxt(data, dtype=[(_, int) for _ in "abc"])

array([(1, 2, 3), (4, 5, 6)],
      dtype=[('a', '<i8'), ('b', '<i8'), ('c', '<i8')])

In [82]:
np.genfromtxt(data, names="A, B, C")

/home/bishal/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: genfromtxt: Empty input file: "<_io.StringIO object at 0x7fd6abc24230>"
  """Entry point for launching an IPython kernel.


array([], dtype=[('A', '<f8'), ('B', '<f8'), ('C', '<f8')])

In [84]:
np.genfromtxt(data, names=True)

/home/bishal/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: genfromtxt: Empty input file: "<_io.StringIO object at 0x7fd6abc24230>"
  """Entry point for launching an IPython kernel.


IndexError: list index out of range

In [86]:
np.genfromtxt(data,names=True)

/home/bishal/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: genfromtxt: Empty input file: "<_io.StringIO object at 0x7fd6abc24230>"
  """Entry point for launching an IPython kernel.


IndexError: list index out of range

In [93]:
data = StringIO("# a b c \n 1 2 3 \n 4 5 6")

In [94]:
np.genfromtxt(data, names=True)

array([(1., 2., 3.), (4., 5., 6.)],
      dtype=[('a', '<f8'), ('b', '<f8'), ('c', '<f8')])

In [95]:
data = StringIO('1 2 3\n4 5 6')

In [96]:
np.genfromtxt(data)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [97]:
np.genfromtxt(data, dtype=(int, int, int))

/home/bishal/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: genfromtxt: Empty input file: "<_io.StringIO object at 0x7fd69f598550>"
  """Entry point for launching an IPython kernel.


array([], dtype=[('f0', '<i8'), ('f1', '<i8'), ('f2', '<i8')])

In [98]:
np.genfromtxt(data, dtype=(int, int, float))

/home/bishal/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: genfromtxt: Empty input file: "<_io.StringIO object at 0x7fd69f598550>"
  """Entry point for launching an IPython kernel.


array([], dtype=[('f0', '<i8'), ('f1', '<i8'), ('f2', '<f8')])

In [102]:
data = StringIO('1 2 3\n 4 5 6')

In [100]:
np.genfromtxt(data, dtype=(int, int, float))

array([(1, 2, 3.), (4, 5, 6.)],
      dtype=[('f0', '<i8'), ('f1', '<i8'), ('f2', '<f8')])

In [103]:
np.genfromtxt(data, dtype=(int, int, float), names='a')

array([(1, 2, 3.), (4, 5, 6.)],
      dtype=[('a', '<i8'), ('f0', '<i8'), ('f1', '<f8')])

In [104]:
data = StringIO("1 2 3\n 4 5 6")

In [107]:
convertfunc= lambda x: str(x)

### converter

In [108]:
np.genfromtxt(data, converters={0:convertfunc})

array([("b'1'", 2., 3.), ("b'4'", 5., 6.)],
      dtype=[('f0', '<U4'), ('f1', '<f8'), ('f2', '<f8')])

In [112]:
np.genfromtxt(data, converters={0:convertfunc})

/home/bishal/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: genfromtxt: Empty input file: "<_io.StringIO object at 0x7fd69f5987d0>"
  """Entry point for launching an IPython kernel.


IndexError: list index out of range

In [113]:
data

In [114]:
np.genfromtxt(data, converters={1:convertfunc})

/home/bishal/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: genfromtxt: Empty input file: "<_io.StringIO object at 0x7fd69f5987d0>"
  """Entry point for launching an IPython kernel.


IndexError: list index out of range

In [130]:
convertfunc= lambda x: int(x)+100

In [124]:
np.genfromtxt(data)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [131]:
data = StringIO("1 2 3\n 4 5 6")

In [132]:
np.genfromtxt(data, converters={0:convertfunc})

array([(101, 2., 3.), (104, 5., 6.)],
      dtype=[('f0', '<i8'), ('f1', '<f8'), ('f2', '<f8')])

In [137]:
data = StringIO("1 2 3\n 4 5 6")
np.genfromtxt(data, names="'a', 'b', 'c'", converters={"a": convertfunc})

array([(101., 2., 3.), (104., 5., 6.)],
      dtype=[('a', '<f8'), ('b', '<f8'), ('c', '<f8')])

## converts can be used based on names or index of columns

### data = StringIO("1 mis 3 ?\n 4 5 6 ?\n 7 mis N/A 10The genfromtxt function provides two other complementary mechanisms: the missing_values argument is used to recognize missing data and a second argument, filling_values, is used to process these missing data.")

In [139]:
np.genfromtxt(data)

array([[ 1., nan,  3., nan],
       [ 4.,  5.,  6., nan],
       [ 7., nan, nan, 10.]])

In [141]:
data = StringIO("1 mis 3 ?\n 4 5 6 ?\n 7 mis N/A 10")
np.genfromtxt(data, missing_values={1:'mis', 2:'N/A', 3:'?'}, filling_values={1:1, 2:2, 3:3})

array([[ 1.,  1.,  3.,  3.],
       [ 4.,  5.,  6.,  3.],
       [ 7.,  1.,  2., 10.]])