# Indexing

## Array indexing refers to any use of the square brackets ([]) to index array values.

In [2]:
import numpy as np
a = np.arange(12).reshape(3,4)

In [3]:
a[0]

array([0, 1, 2, 3])

In [4]:
a[0,0]

0

In [5]:
a[0][0]

0

In [6]:
a[-2]

array([4, 5, 6, 7])

In [7]:
x = a.copy()

In [8]:
x is a

False

In [9]:
x.base is a

False

In [11]:
x.flags.owndata

True

In [14]:
print(x.base)

None


In [19]:
x.shape

(3, 4)

In [20]:
x.shape = 4,3

In [21]:
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

#### Note that if one indexes a multidimensional array with fewer indices than dimensions, one gets a subdimensional array. For example:

In [23]:
x[0]

array([0, 1, 2])

In [25]:
x[0].base is x

True

In [26]:
x[0].view() is x[0]

False

In [34]:
x[0].view().base is x

True

In [38]:
b = a.reshape(2,3,2)

In [39]:
b[0]

array([[0, 1],
       [2, 3],
       [4, 5]])

## So note that x[0,2] = x[0][2] though the second case is more inefficient as a new temporary array is created after the first index that is subsequently indexed by 2.

In [40]:
%timeit x[0,2]

184 ns ± 3.35 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


### x[0][2] is inefficient as new temp array is created after the first index

In [41]:
%timeit x[0][2]

362 ns ± 3.94 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [42]:
x = np.arange(12)

In [43]:
x[2:5]

array([2, 3, 4])

In [44]:
x[2]

2

In [45]:
x[:-7]

array([0, 1, 2, 3, 4])

In [46]:
x[1:7:2]

array([1, 3, 5])

In [47]:
x = np.arange(35).reshape(5,-1)

In [48]:
x

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

## commasepareted dimensions

In [49]:
x[1:5:2, :]

array([[ 7,  8,  9, 10, 11, 12, 13],
       [21, 22, 23, 24, 25, 26, 27]])

In [50]:
x[1:5:2, :4:2]

array([[ 7,  9],
       [21, 23]])

## Index Arrays

In [51]:
x

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

# INDEXING IS ONLY POSSIBLE BY INTEGERS NOT BY FLOATING VALUES

In [52]:
i = np.array([1,2,3,1,])

In [53]:
x[i] # passing array as index

array([[ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [ 7,  8,  9, 10, 11, 12, 13]])

In [54]:
x[[1,2,3,1]]

array([[ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [ 7,  8,  9, 10, 11, 12, 13]])

### NumPy arrays may be indexed with other arrays (or any other sequence- like object that can be converted to an array, such as lists, with the exception of tuples;

In [55]:
x[(1,2,3,1)]

IndexError: too many indices for array

### . For all cases of index arrays, what is returned is a copy of the original data, not a view as one gets for slices.

#### Negative values are permitted and work as they do with single indices or slices:

In [56]:
x[np.array((1,-1,1,1))]

array([[ 7,  8,  9, 10, 11, 12, 13],
       [28, 29, 30, 31, 32, 33, 34],
       [ 7,  8,  9, 10, 11, 12, 13],
       [ 7,  8,  9, 10, 11, 12, 13]])

In [57]:
x[[[1,1],[3,1]]]

/home/bishal/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  """Entry point for launching an IPython kernel.


array([10,  8])

In [58]:
x

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [64]:
x[np.array([np.arange(4).reshape(2,2)])]

array([[[[ 0,  1,  2,  3,  4,  5,  6],
         [ 7,  8,  9, 10, 11, 12, 13]],

        [[14, 15, 16, 17, 18, 19, 20],
         [21, 22, 23, 24, 25, 26, 27]]]])

In [65]:
np.arange(4).reshape(2,-1)

array([[0, 1],
       [2, 3]])

In [66]:
x[np.arange(4).reshape(2,-1)]

array([[[ 0,  1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12, 13]],

       [[14, 15, 16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25, 26, 27]]])

In [67]:
x[np.arange(3), np.arange(3)]

array([ 0,  8, 16])

In [68]:
x[[np.arange(3), np.arange(3)], [np.arange(3), np.arange(3)]]

array([[ 0,  8, 16],
       [ 0,  8, 16]])

In [70]:
x[np.array([0,2,4]), np.array([0,1])]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [71]:
x[np.array((0,1,3))]

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [21, 22, 23, 24, 25, 26, 27]])

# What results is the construction of a new array where each value of the index array selects one row from the array being indexed and the resultant array has the resulting shape (number of index elements, size of row).

## Boolean arrays must be of the same shape as the initial dimensions of the array being indexed

In [72]:
b = x > 20

In [73]:
b

array([[False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

##### boolean indexing

In [74]:
x[b]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

## Unlike in the case of integer index arrays, in the boolean case, the result is a 1-D array containing all the elements in the indexed array corresponding to all the true elements in the boolean array.

In [75]:
x[np.nonzero(b)]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

### both x[b] as x[np.nonzero(b)] is same

In [76]:
b[:,5]

array([False, False, False,  True,  True])

In [77]:
x[b[:,5]]

array([[21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [78]:
x[[3,4],:]

array([[21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [81]:
x[np.array([0,1,2,3]), 1:4]

array([[ 1,  2,  3],
       [ 8,  9, 10],
       [15, 16, 17],
       [22, 23, 24]])

# elipsis syntax :

In [82]:
x.dtype

dtype('int64')

In [85]:
x[1,1] = 1.2

### 1.2 converted to dtype of x if possible

In [86]:
x

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  1,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [88]:
x.dtype = float

In [90]:
x

array([[0.00e+000, 4.94e-324, 9.88e-324, 1.48e-323, 1.98e-323, 2.47e-323,
        2.96e-323],
       [3.46e-323, 4.94e-324, 4.45e-323, 4.94e-323, 5.43e-323, 5.93e-323,
        6.42e-323],
       [6.92e-323, 7.41e-323, 7.91e-323, 8.40e-323, 8.89e-323, 9.39e-323,
        9.88e-323],
       [1.04e-322, 1.09e-322, 1.14e-322, 1.19e-322, 1.24e-322, 1.28e-322,
        1.33e-322],
       [1.38e-322, 1.43e-322, 1.48e-322, 1.53e-322, 1.58e-322, 1.63e-322,
        1.68e-322]])

In [91]:
x[2,3] = 3

In [92]:
x[2,3]

3.0

In [93]:
x[2,4] = 3j

TypeError: can't convert complex to float

### Note that assignments may result in changes if assigning higher types to lower types (like floats to ints) or even exceptions (assigning complex to floats or ints):