# Array creation¶


In [2]:
import numpy as np
np.array([1,1,1,])

array([1, 1, 1])

In [4]:
np.array(tuple((1,2,3,4)))

array([1, 2, 3, 4])

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.eye((4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
np.eye((3,4))

TypeError: 'tuple' object cannot be interpreted as an integer

In [12]:
np.linspace(3,5,5) # starting, endpoint and number of elements guarenteed using np.linspace()

array([3. , 3.5, 4. , 4.5, 5. ])

In [14]:
np.arange(1,10,3) # starting and difference guarented not endpoint and number

array([1, 4, 7])

In [17]:
np.indices((1,))

array([[0]])

In [18]:
np.indices((1,1,))

array([[[0]],

       [[0]]])

In [20]:
a = np.indices((2,2))

In [21]:
a.shape

(2, 2, 2)

In [22]:
a

array([[[0, 0],
        [1, 1]],

       [[0, 1],
        [0, 1]]])

In [23]:
np.indices((3,))

array([[0, 1, 2]])

In [24]:
np.indices((3,1))

array([[[0],
        [1],
        [2]],

       [[0],
        [0],
        [0]]])

# Working with IO

## Importing data with genfromtxt

In [26]:
import numpy as np
from io import StringIO

In [27]:
data = u"1, 2, 3, 4\n5, 6, 7, 8"

In [28]:
type(data)

str

In [29]:
repr(data)

"'1, 2, 3, 4\\n5, 6, 7, 8'"

In [30]:
np.genfromtxt(StringIO(data), delimiter=',')

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

###### The delimiter keyword is used to define how the splitting should take place

In [35]:
np.genfromtxt(StringIO('datas/csvtorandomize.csv'), delimiter=',')

array(nan)

In [35]:
np.genfromtxt(StringIO('datas/csvtorandomize.csv'), delimiter=',')

array(nan)

In [42]:
np.genfromtxt(StringIO('datas/csv_to_randomize.csv'), delimiter=None)

array(nan)

In [34]:
ls datas/

class11datacollection.csv      Class11DataCollection.xlsx  csvtorandomize.csv
class11datacollection.csv.csv  csv_to_randomize.csv        gopalsanclean.csv


In [43]:
data = u"  1  2  3\n  4  5 67\n890123  4"

In [44]:
np.genfromtxt(StringIO(data), delimiter=3)

array([[  1.,   2.,   3.],
       [  4.,   5.,  67.],
       [890., 123.,   4.]])

In [54]:
data = u"  1  2  3\n  4  5 67\n890123  4"


In [55]:

np.genfromtxt(StringIO(data), delimiter=3)

array([[  1.,   2.,   3.],
       [  4.,   5.,  67.],
       [890., 123.,   4.]])

In [74]:
data = u"123456789\n   4  7 9\n   4567999"

In [75]:
np.genfromtxt(StringIO(data), delimiter=(4, 3, 2))

array([[1234.,  567.,   89.],
       [   4.,    7.,    9.],
       [   4.,  567.,   99.]])