In [1]:
import numpy as np

a = np.arange(15).reshape(3,5)

In [2]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
a.shape

(3, 5)

In [4]:
a.ndim

2

In [5]:
a.dtype

dtype('int64')

In [6]:
a.dtype.name

'int64'

In [8]:
a.itemsize # 64/8

8

In [10]:
type(a)

numpy.ndarray

In [11]:
b = np.array([4,3,3])

In [12]:
type(b)

numpy.ndarray

In [14]:
b

array([4, 3, 3])

In [15]:
a = np.array((1,2,3))

In [17]:
a

array([1, 2, 3])

In [18]:
type(a)

numpy.ndarray

In [19]:
a = np.array((1,1.1,3))

In [20]:
a.dtype

dtype('float64')

In [21]:
a

array([1. , 1.1, 3. ])

In [22]:
a.shape

(3,)

In [23]:
a = np.array(((1,2,3), (3,4,5)))

In [24]:
a

array([[1, 2, 3],
       [3, 4, 5]])

In [30]:
a = np.array((1,2,3.1), dtype=int)

In [31]:
a

array([1, 2, 3])

In [32]:
c = np.array([1,2,3], dtype=complex)

In [33]:
c

array([1.+0.j, 2.+0.j, 3.+0.j])

In [35]:
z = np.zeros((3,4))

In [36]:
z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
np.ones((1,2))

array([[1., 1.]])

In [38]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [40]:
np.empty((2,3)) # gives random aray based on current state of memory


array([[1., 1., 1.],
       [1., 1., 1.]])

In [41]:
np.ones((2,3))*2

array([[2., 2., 2.],
       [2., 2., 2.]])

In [42]:
np.empty((3,3))

array([[4.65624985e-310, 0.00000000e+000, 2.37663529e-312],
       [2.56761491e-312, 8.48798317e-313, 9.33678148e-313],
       [8.70018275e-313, 6.91452328e-310, 5.42577449e-109]])

In [47]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [49]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
np.arange(1,3,0.3)

array([1. , 1.3, 1.6, 1.9, 2.2, 2.5, 2.8])

In [52]:
np.linspace(10,20,9)

array([10.  , 11.25, 12.5 , 13.75, 15.  , 16.25, 17.5 , 18.75, 20.  ])

In [57]:
 t = np.arange(0,181, 30)

In [62]:
np.sin(t)

array([ 0.        , -0.98803162, -0.30481062,  0.89399666,  0.58061118,
       -0.71487643, -0.80115264])

In [59]:
t

array([  0,  30,  60,  90, 120, 150, 180])

In [63]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [65]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [66]:
a = np.arange(1,10).reshape(3,3)

In [67]:
b = np.arange(1,10).reshape(3,3)

In [68]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
a*b # element wise product

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [71]:
a@b # matrix method

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [72]:
a.dot(b) # matrix method

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [74]:
np.random.random(3)

array([0.6666588 , 0.56401305, 0.08069726])

In [75]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
a *= 3

In [77]:
a

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [78]:
a += b

In [79]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [80]:
a

array([[ 4,  8, 12],
       [16, 20, 24],
       [28, 32, 36]])

In [83]:
c = np.ones((3,3),dtype=np.float32)

In [84]:
a+c

array([[ 5.,  9., 13.],
       [17., 21., 25.],
       [29., 33., 37.]])

In [85]:
a += c

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [86]:
np.exp([1,0,0,1])

array([2.71828183, 1.        , 1.        , 2.71828183])

In [87]:
np.log([2.71828183, 1.        , 1.        , 2.71828183])

array([1., 0., 0., 1.])

In [88]:
np.random.random(3)

array([0.64877843, 0.59170298, 0.47007379])

In [89]:
a.sum()

180

In [90]:
a.min()

4

In [91]:
a.max()

36

In [92]:
b = np.arange(12).reshape(3,4)

In [93]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [94]:
b.sum() 

66

In [95]:
b.sum(axis=0) # sum of each column

array([12, 15, 18, 21])

In [96]:
b.sum(axis=1) # sum of each row

array([ 6, 22, 38])

In [97]:
b.min(axis=0) # min in each axis

array([0, 1, 2, 3])

In [98]:
b.max(axis=1)

array([ 3,  7, 11])

In [99]:
b.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66])

In [100]:
b.cumsum(axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]])

In [101]:
b.cumprod(axis=0)

array([[  0,   1,   2,   3],
       [  0,   5,  12,  21],
       [  0,  45, 120, 231]])

In [102]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [103]:
a

array([[ 4,  8, 12],
       [16, 20, 24],
       [28, 32, 36]])

In [104]:
b = a*a

In [105]:
b

array([[  16,   64,  144],
       [ 256,  400,  576],
       [ 784, 1024, 1296]])

In [106]:
np.sqrt(b)

array([[ 4.,  8., 12.],
       [16., 20., 24.],
       [28., 32., 36.]])

In [107]:
np.add(a,a)

array([[ 8, 16, 24],
       [32, 40, 48],
       [56, 64, 72]])

In [108]:
a.mean()

20.0

In [109]:
a.mean(axis=0)

array([16., 20., 24.])

In [111]:
a = np.arange(10)*3

In [112]:
a

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [113]:
a[::-1]

array([27, 24, 21, 18, 15, 12,  9,  6,  3,  0])

In [114]:
a[:4:2] = 200

In [115]:
a

array([200,   3, 200,   9,  12,  15,  18,  21,  24,  27])

In [117]:
a**(1/7)

array([2.13166312, 1.16993081, 2.13166312, 1.36873811, 1.42616164,
       1.4723567 , 1.51120939, 1.54485766, 1.57461011, 1.60132889])

In [119]:
def func(x,y):
    return 10*x+y

np.fromfunction(func, (2,2))

array([[ 0.,  1.],
       [10., 11.]])

In [121]:
def func(x,y):
    return 10*x+y

np.fromfunction(func, (2,3))

array([[ 0.,  1.,  2.],
       [10., 11., 12.]])

In [122]:
help(np.fromfunction)

Help on function fromfunction in module numpy:

fromfunction(function, shape, **kwargs)
    Construct an array by executing a function over each coordinate.
    
    The resulting array therefore has a value ``fn(x, y, z)`` at
    coordinate ``(x, y, z)``.
    
    Parameters
    ----------
    function : callable
        The function is called with N parameters, where N is the rank of
        `shape`.  Each parameter represents the coordinates of the array
        varying along a specific axis.  For example, if `shape`
        were ``(2, 2)``, then the parameters would be
        ``array([[0, 0], [1, 1]])`` and ``array([[0, 1], [0, 1]])``
    shape : (N,) tuple of ints
        Shape of the output array, which also determines the shape of
        the coordinate arrays passed to `function`.
    dtype : data-type, optional
        Data-type of the coordinate arrays passed to `function`.
        By default, `dtype` is float.
    
    Returns
    -------
    fromfunction : any
        The 

In [123]:
b

array([[  16,   64,  144],
       [ 256,  400,  576],
       [ 784, 1024, 1296]])

In [124]:
b[:2]

array([[ 16,  64, 144],
       [256, 400, 576]])

In [125]:
b[0]

array([ 16,  64, 144])

In [126]:
b[:,1]

array([  64,  400, 1024])

In [129]:
b[0:3,1] # b01 b11 b21

array([  64,  400, 1024])

In [130]:
b[0,1]

64

In [132]:
b[1:3, :]

array([[ 256,  400,  576],
       [ 784, 1024, 1296]])

In [133]:
b[1,:]

array([256, 400, 576])

In [134]:
b[1:]

array([[ 256,  400,  576],
       [ 784, 1024, 1296]])

In [135]:
b[1:,1
]

array([ 400, 1024])

In [139]:
b[:,:]

array([[  16,   64,  144],
       [ 256,  400,  576],
       [ 784, 1024, 1296]])

In [140]:
b[-1]


array([ 784, 1024, 1296])

In [141]:
b[1,2]

576

In [143]:
b[1] [2]

576

In [147]:
b

array([[  16,   64,  144],
       [ 256,  400,  576],
       [ 784, 1024, 1296]])

In [148]:
b[1,:]

array([256, 400, 576])

In [149]:
b[1]

array([256, 400, 576])

In [150]:
b[1,...]

array([256, 400, 576])

In [155]:
b[-1]

array([ 784, 1024, 1296])

In [156]:
c = np.arange(12).reshape(2,2,3)

In [157]:
c

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [158]:
c.shape

(2, 2, 3)

In [159]:
c.ndim

3

In [163]:
c[1].ndim

2

In [164]:
c[1]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [165]:
c[1,...]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [167]:
c[1, 1]

array([ 9, 10, 11])

In [168]:
c[1,1,1]

10

In [169]:
c[:,1,1]

array([ 4, 10])

In [170]:
c

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [171]:
c.flat

In [172]:
list(c.flat)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [174]:
a = np.floor(10* np.random.random((2,3)))

In [175]:
a

array([[1., 4., 3.],
       [5., 5., 9.]])

In [177]:
a.shape

(2, 3)

In [182]:
a.ravel() # flattens and returns a numpy array

array([1., 4., 3., 5., 5., 9.])

In [183]:
a.reshape(3,2)

array([[1., 4.],
       [3., 5.],
       [5., 9.]])

In [184]:
a

array([[1., 4., 3.],
       [5., 5., 9.]])

In [185]:
a.T # transpose

array([[1., 5.],
       [4., 5.],
       [3., 9.]])

In [186]:
print(a.shape)
print(a.T.shape)
print(a.T.T.shape)

(2, 3)
(3, 2)
(2, 3)


In [187]:
a

array([[1., 4., 3.],
       [5., 5., 9.]])

In [188]:

a.resize((3,3))

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [192]:
a = np.arange(12).reshape(4,3)
# a.resize((3,4))

In [193]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [194]:
a.resize((3,4))

In [195]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [196]:
a.reshape(6,-1)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [197]:
a = np.floor(10*np.random.random((2,2)))

In [198]:
b = np.floor(10*np.random.random((2,2)))

In [199]:
a

array([[4., 4.],
       [5., 2.]])

In [200]:
b

array([[4., 9.],
       [5., 3.]])

In [201]:
np.vstack((a,b))

array([[4., 4.],
       [5., 2.],
       [4., 9.],
       [5., 3.]])

In [202]:
np.hstack((a,b))

array([[4., 4., 4., 9.],
       [5., 2., 5., 3.]])

In [206]:
from numpy import newaxis
np.column_stack((a,b))

array([[4., 4., 4., 9.],
       [5., 2., 5., 3.]])

In [207]:
a = np.array([1,3])

In [208]:
b = np.array([3,9])

In [210]:
np.hstack((a,b))

array([1, 3, 3, 9])

In [211]:
np.vstack((a,b))

array([[1, 3],
       [3, 9]])

In [212]:
np.vstack((a,b)).shape

(2, 2)

In [213]:
np.column_stack((a,b))

array([[1, 3],
       [3, 9]])

In [214]:
a

array([1, 3])

In [217]:
b = a[:,newaxis]

In [218]:
a.shape


(2,)

In [221]:
a.reshape(2,1)

array([[1],
       [3]])

In [222]:
a

array([1, 3])

In [219]:
b

array([[1],
       [3]])

In [220]:
b.shape

(2, 1)

In [223]:
a

array([1, 3])

In [224]:
b

array([[1],
       [3]])

In [226]:
np.column_stack((b,b))

array([[1, 1],
       [3, 3]])

In [227]:
np.column_stack((a,a))


array([[1, 1],
       [3, 3]])

In [228]:
np.vstack((a,a))

array([[1, 3],
       [1, 3]])

In [229]:
np.r_[1:4,0,4]

array([1, 2, 3, 0, 4])

In [230]:
np.array([1:4])

SyntaxError: invalid syntax (<ipython-input-230-70a69fd8a061>, line 1)

In [233]:
c= np.c_[1,4,5]

In [234]:
print(c)

[[1 4 5]]


In [235]:
c.shape

(1, 3)

In [249]:
a = a.reshape(1,2)

In [242]:
b = b.reshape(1,2)

In [243]:
b

array([[1, 3]])

In [251]:
np.concatenate((a,b))

array([[1, 3],
       [1, 3]])

In [250]:
print(a.shape)
print(b.shape)

(1, 2)
(1, 2)


In [252]:
a = np.arange(10).reshape(2,5)

In [254]:
b = np.arange(10,20).reshape(2,5)

In [255]:
np.concatenate((a,b))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### Splitting one array into several smaller ones¶

In [256]:
a = np.floor(10*np.random.random((2,12)))

In [257]:
a

array([[5., 4., 5., 7., 7., 2., 9., 9., 1., 8., 3., 4.],
       [4., 1., 8., 4., 9., 8., 8., 5., 9., 7., 3., 8.]])

In [258]:
np.hsplit(a, 3)

[array([[5., 4., 5., 7.],
        [4., 1., 8., 4.]]),
 array([[7., 2., 9., 9.],
        [9., 8., 8., 5.]]),
 array([[1., 8., 3., 4.],
        [9., 7., 3., 8.]])]

In [259]:
np.hsplit(a,4)

[array([[5., 4., 5.],
        [4., 1., 8.]]),
 array([[7., 7., 2.],
        [4., 9., 8.]]),
 array([[9., 9., 1.],
        [8., 5., 9.]]),
 array([[8., 3., 4.],
        [7., 3., 8.]])]

In [260]:
np.hsplit(a,5)

ValueError: array split does not result in an equal division

In [263]:
np.hsplit(a, (3,4)) # Split a after the third and the fourth column

[array([[5., 4., 5.],
        [4., 1., 8.]]),
 array([[7.],
        [4.]]),
 array([[7., 2., 9., 9., 1., 8., 3., 4.],
        [9., 8., 8., 5., 9., 7., 3., 8.]])]

In [264]:
a

array([[5., 4., 5., 7., 7., 2., 9., 9., 1., 8., 3., 4.],
       [4., 1., 8., 4., 9., 8., 8., 5., 9., 7., 3., 8.]])

In [269]:
np.vsplit(a.reshape(6,4), 2)

[array([[5., 4., 5., 7.],
        [7., 2., 9., 9.],
        [1., 8., 3., 4.]]),
 array([[4., 1., 8., 4.],
        [9., 8., 8., 5.],
        [9., 7., 3., 8.]])]

In [273]:
b = a.reshape(6,4)

In [275]:
np.vsplit(b, 3)

[array([[5., 4., 5., 7.],
        [7., 2., 9., 9.]]),
 array([[1., 8., 3., 4.],
        [4., 1., 8., 4.]]),
 array([[9., 8., 8., 5.],
        [9., 7., 3., 8.]])]

In [276]:
np.hsplit(a, (1,2))

[array([[5.],
        [4.]]),
 array([[4.],
        [1.]]),
 array([[5., 7., 7., 2., 9., 9., 1., 8., 3., 4.],
        [8., 4., 9., 8., 8., 5., 9., 7., 3., 8.]])]

In [277]:
a

array([[5., 4., 5., 7., 7., 2., 9., 9., 1., 8., 3., 4.],
       [4., 1., 8., 4., 9., 8., 8., 5., 9., 7., 3., 8.]])

In [2]:
import numpy as np
a = np.arange(10)

In [3]:
b = a

In [4]:
b is a


True

In [5]:
b.shape

(10,)

In [8]:
b = b.reshape(5,2)

In [9]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [11]:
b is a

False

In [12]:
a = np.arange(12)

In [13]:
b =a

In [14]:
b is a

True

In [15]:
b.shape = 3,4

In [16]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# View or Shallow Copy

In [21]:
c  = a.view()

In [22]:
c is a

False

In [26]:
c[0] is a[0]

False

In [28]:
c.base is a # c is the view of data owned by a

True

In [29]:
help(c.base)

Help on ndarray object:

class ndarray(builtins.object)
 |  ndarray(shape, dtype=float, buffer=None, offset=0,
 |          strides=None, order=None)
 |  
 |  An array object represents a multidimensional, homogeneous array
 |  of fixed-size items.  An associated data-type object describes the
 |  format of each element in the array (its byte-order, how many bytes it
 |  occupies in memory, whether it is an integer, a floating point number,
 |  or something else, etc.)
 |  
 |  Arrays should be constructed using `array`, `zeros` or `empty` (refer
 |  to the See Also section below).  The parameters given here refer to
 |  a low-level method (`ndarray(...)`) for instantiating an array.
 |  
 |  For more information, refer to the `numpy` module and examine the
 |  methods and attributes of an array.
 |  
 |  Parameters
 |  ----------
 |  (for the __new__ method; see Notes below)
 |  
 |  shape : tuple of ints
 |      Shape of created array.
 |  dtype : data-type, optional
 |      Any objec

In [30]:
d = c.view()

In [31]:
d is c

False

In [32]:
d.base is c

False

In [33]:
d.base is a

True

In [34]:
c.flags.owndata

False

In [35]:
a.flags.owndata

True

In [36]:
d.flags.owndata

False

In [37]:
c.shape

(3, 4)

In [38]:
c.shape = 2,6

In [40]:
a.shape

(3, 4)

In [41]:
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [42]:
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
c[0,4]

4

In [44]:
c[0,4] = 44

In [45]:
a

array([[ 0,  1,  2,  3],
       [44,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [46]:
c.base is a

True

In [47]:
d

array([[ 0,  1,  2,  3],
       [44,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
c

array([[ 0,  1,  2,  3, 44,  5],
       [ 6,  7,  8,  9, 10, 11]])

### base data changes when changing the data in view/ shallow copy 

# Slicing an array returns a view of it:



In [49]:
a [:, 2:4]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [51]:
e = a[:, 2:4]

In [52]:
e.flags.owndata

False

In [53]:
e.base

array([[ 0,  1,  2,  3],
       [44,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [55]:
id(e.base) ==  id(a)

True

In [56]:
e[:] = 10

In [57]:
a

array([[ 0,  1, 10, 10],
       [44,  5, 10, 10],
       [ 8,  9, 10, 10]])

In [58]:
e

array([[10, 10],
       [10, 10],
       [10, 10]])

In [59]:
f = a[:, 2:4]

In [60]:
f = 10

In [61]:
e

array([[10, 10],
       [10, 10],
       [10, 10]])

In [62]:
a

array([[ 0,  1, 10, 10],
       [44,  5, 10, 10],
       [ 8,  9, 10, 10]])

In [63]:
f

10

In [65]:
f.flags.owndata

AttributeError: 'int' object has no attribute 'flags'

# Deep Copy

### The copy method makes a complete copy of the array and its data

In [66]:
a

array([[ 0,  1, 10, 10],
       [44,  5, 10, 10],
       [ 8,  9, 10, 10]])

In [71]:
d = a.copy() # new array object is created with new data of a

In [72]:
d is a

False

In [73]:
d.base is a

False

In [76]:
d[0,0] = 1999

In [77]:
a

array([[ 0,  1, 10, 10],
       [44,  5, 10, 10],
       [ 8,  9, 10, 10]])

In [79]:
d

array([[1999,    1,   10,   10],
       [  44,    5,   10,   10],
       [   8,    9,   10,   10]])

In [80]:
a = np.arange(int(1e8))

In [81]:
b = a[:100].copy()

In [82]:
del a

In [84]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

### If b = a[:100] is used instead, a is referenced by b and will persist in memory even if del a is executed.

In [85]:
c  = b[:]

In [86]:
del c

In [87]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [90]:
d = b[:]

In [91]:
del b

In [95]:
b

NameError: name 'b' is not defined

In [96]:
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [104]:
c = np.arange(10).reshape(2,5)
np.diagonal(c)

array([0, 6])

## Indexing with Arrays of Indices¶


In [106]:
a = np.arange(12)**2

In [117]:
i = np.array([1,3,3,5,8]) # array of indices

In [111]:
a[i]

array([ 1,  9,  9, 25, 64])

In [114]:
a[np.array([1,2,3])]

array([1, 4, 9])

In [118]:
j = np.array([[3,4], [5,6]]) # a bidimensional array of indices

In [119]:
 b = a[j]

In [120]:
b[1,1]

36

In [121]:
a = np.arange(12).reshape(3,4)

In [122]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [123]:
i = np.array([0,1,1,0])

In [124]:
a[i]

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [4, 5, 6, 7],
       [0, 1, 2, 3]])

In [129]:
j = np.array([[[0,1]],[[1,0]]])

In [130]:
a[j]

array([[[[0, 1, 2, 3],
         [4, 5, 6, 7]]],


       [[[4, 5, 6, 7],
         [0, 1, 2, 3]]]])

In [137]:
i = np.array([[0,1], [2,1]])
j = np.array([[2,0], [3,2]])

In [138]:
a[i,j]

array([[ 2,  4],
       [11,  6]])

In [135]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [139]:
a[:,j]

array([[[ 2,  0],
        [ 3,  2]],

       [[ 6,  4],
        [ 7,  6]],

       [[10,  8],
        [11, 10]]])

In [142]:
a[(2,2), (0,1)]

array([8, 9])

In [144]:
a.argmax()

11

In [145]:
a.argmax(axis=0)

array([2, 2, 2, 2])

In [146]:
ind = a.argmax(axis=0)

In [148]:
a =np.floor(10*np.random.random((3,4)))

In [149]:
a

array([[6., 3., 8., 9.],
       [8., 6., 2., 8.],
       [3., 5., 2., 0.]])

In [150]:
a.argmax(axis=1)

array([3, 0, 1])

In [151]:
ind = a.argmax(axis=1)


In [157]:
a.shape[0]

3

In [158]:
a[np.arange(a.shape[0]), ind]

array([9., 8., 5.])

In [159]:
np.all

<function numpy.all(a, axis=None, out=None, keepdims=<no value>)>

In [161]:
np.all(a, axis=1)

array([ True,  True, False])

In [162]:
np.any(a)

True

In [164]:
np.any(a>10, axis=0)

array([False, False, False, False])

In [165]:
a

array([[6., 3., 8., 9.],
       [8., 6., 2., 8.],
       [3., 5., 2., 0.]])

In [166]:
a = np.arange(5)

In [168]:
a[[0,0,2]] = 3

In [169]:
a

array([3, 1, 3, 3, 4])

In [170]:
a

array([3, 1, 3, 3, 4])

In [171]:
a += 1

In [172]:
a

array([4, 2, 4, 4, 5])

In [173]:
a[:] += 1

In [174]:
a

array([5, 3, 5, 5, 6])

In [175]:
a.copy()+1

array([6, 4, 6, 6, 7])

In [176]:
a

array([5, 3, 5, 5, 6])

## Indexing with Boolean Arrays¶


In [180]:
a = (np.arange(1,13)**2).reshape(3,4)

In [181]:
a

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [182]:
bol = a%2==0

In [183]:
bol

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [184]:
a[bol]

array([  4,  16,  36,  64, 100, 144])

In [186]:
help(np.ogrid)

Help on OGridClass in module numpy.lib.index_tricks object:

class OGridClass(nd_grid)
 |  `nd_grid` instance which returns an open multi-dimensional "meshgrid".
 |  
 |  An instance of `numpy.lib.index_tricks.nd_grid` which returns an open
 |  (i.e. not fleshed out) mesh-grid when indexed, so that only one dimension
 |  of each returned array is greater than 1.  The dimension and number of the
 |  output arrays are equal to the number of indexing dimensions.  If the step
 |  length is not a complex number, then the stop is not inclusive.
 |  
 |  However, if the step length is a **complex number** (e.g. 5j), then
 |  the integer part of its magnitude is interpreted as specifying the
 |  number of points to create between the start and stop values, where
 |  the stop value **is inclusive**.
 |  
 |  Returns
 |  -------
 |  mesh-grid
 |      `ndarrays` with only one dimension not equal to 1
 |  
 |  See Also
 |  --------
 |  np.lib.index_tricks.nd_grid : class of `ogrid` and `mgrid` obj

In [200]:
a = np.arange(4).reshape(4,-1)

In [201]:
b = np.arange(4).reshape(1,4)

In [202]:
a*b

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])

In [208]:
a = np.ix_(np.arange(6)**2, np.arange(10))

In [209]:
a

(array([[ 0],
        [ 1],
        [ 4],
        [ 9],
        [16],
        [25]]),
 array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]))

In [211]:
a = np.arange(9).reshape(3,3,)

In [212]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [214]:
np.trace(a)

12

In [215]:
a[1,1] = 12

In [216]:
np.trace(a)

20

In [217]:
np.linalg.inv(a)

array([[-0.63541667, -0.0625    ,  0.19791667],
       [-0.0625    ,  0.125     , -0.0625    ],
       [ 0.53125   , -0.0625    ,  0.03125   ]])

In [219]:
y = np.arange(3).reshape(3,1)

In [222]:
np.linalg.solve(np.eye((3)),y)

array([[0.],
       [1.],
       [2.]])

### Automatic” Reshaping¶
using -1 

In [223]:
a

array([[ 0,  1,  2],
       [ 3, 12,  5],
       [ 6,  7,  8]])

In [224]:
a = np.arange(18).reshape(9,2)

In [225]:
a.reshape(3,-1,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]])

# The fixed size of NumPy numeric types may cause overflow errors when a value requires more memory than available in the data type.

In [227]:
a = np.ones(4, dtype=np.int8)

In [228]:
a

array([1, 1, 1, 1], dtype=int8)

In [230]:
a[0] = 14444

In [231]:
a

array([108,   1,   1,   1], dtype=int8)

# Overflow error cause the value of a[0] to be something different 

## NumPy provides numpy.iinfo and numpy.finfo to verify the minimum or maximum values of NumPy integer and floating point values respectively

In [236]:
np.iinfo(int)

iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)

In [238]:
np.finfo(float)

finfo(resolution=1e-15, min=-1.7976931348623157e+308, max=1.7976931348623157e+308, dtype=float64)

In [241]:
np.iinfo(np.int8)

iinfo(min=-128, max=127, dtype=int8)

In [242]:
np.finfo(np.float64)

finfo(resolution=1e-15, min=-1.7976931348623157e+308, max=1.7976931348623157e+308, dtype=float64)

In [243]:
np.iinfo(int)

iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)