In [1]:
import numpy as np

a = np.arange(15).reshape(3,5)

In [2]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
a.shape

(3, 5)

In [4]:
a.ndim

2

In [5]:
a.dtype

dtype('int64')

In [6]:
a.dtype.name

'int64'

In [8]:
a.itemsize # 64/8

8

In [10]:
type(a)

numpy.ndarray

In [11]:
b = np.array([4,3,3])

In [12]:
type(b)

numpy.ndarray

In [14]:
b

array([4, 3, 3])

In [15]:
a = np.array((1,2,3))

In [17]:
a

array([1, 2, 3])

In [18]:
type(a)

numpy.ndarray

In [19]:
a = np.array((1,1.1,3))

In [20]:
a.dtype

dtype('float64')

In [21]:
a

array([1. , 1.1, 3. ])

In [22]:
a.shape

(3,)

In [23]:
a = np.array(((1,2,3), (3,4,5)))

In [24]:
a

array([[1, 2, 3],
       [3, 4, 5]])

In [30]:
a = np.array((1,2,3.1), dtype=int)

In [31]:
a

array([1, 2, 3])

In [32]:
c = np.array([1,2,3], dtype=complex)

In [33]:
c

array([1.+0.j, 2.+0.j, 3.+0.j])

In [35]:
z = np.zeros((3,4))

In [36]:
z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
np.ones((1,2))

array([[1., 1.]])

In [38]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [40]:
np.empty((2,3)) # gives random aray based on current state of memory


array([[1., 1., 1.],
       [1., 1., 1.]])

In [41]:
np.ones((2,3))*2

array([[2., 2., 2.],
       [2., 2., 2.]])

In [42]:
np.empty((3,3))

array([[4.65624985e-310, 0.00000000e+000, 2.37663529e-312],
       [2.56761491e-312, 8.48798317e-313, 9.33678148e-313],
       [8.70018275e-313, 6.91452328e-310, 5.42577449e-109]])

In [47]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [49]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
np.arange(1,3,0.3)

array([1. , 1.3, 1.6, 1.9, 2.2, 2.5, 2.8])

In [52]:
np.linspace(10,20,9)

array([10.  , 11.25, 12.5 , 13.75, 15.  , 16.25, 17.5 , 18.75, 20.  ])

In [57]:
 t = np.arange(0,181, 30)

In [62]:
np.sin(t)

array([ 0.        , -0.98803162, -0.30481062,  0.89399666,  0.58061118,
       -0.71487643, -0.80115264])

In [59]:
t

array([  0,  30,  60,  90, 120, 150, 180])

In [63]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [65]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [66]:
a = np.arange(1,10).reshape(3,3)

In [67]:
b = np.arange(1,10).reshape(3,3)

In [68]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
a*b # element wise product

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [71]:
a@b # matrix method

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [72]:
a.dot(b) # matrix method

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [74]:
np.random.random(3)

array([0.6666588 , 0.56401305, 0.08069726])

In [75]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
a *= 3

In [77]:
a

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [78]:
a += b

In [79]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [80]:
a

array([[ 4,  8, 12],
       [16, 20, 24],
       [28, 32, 36]])

In [83]:
c = np.ones((3,3),dtype=np.float32)

In [84]:
a+c

array([[ 5.,  9., 13.],
       [17., 21., 25.],
       [29., 33., 37.]])

In [85]:
a += c

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [86]:
np.exp([1,0,0,1])

array([2.71828183, 1.        , 1.        , 2.71828183])

In [87]:
np.log([2.71828183, 1.        , 1.        , 2.71828183])

array([1., 0., 0., 1.])

In [88]:
np.random.random(3)

array([0.64877843, 0.59170298, 0.47007379])

In [89]:
a.sum()

180

In [90]:
a.min()

4

In [91]:
a.max()

36

In [92]:
b = np.arange(12).reshape(3,4)

In [93]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [94]:
b.sum() 

66

In [95]:
b.sum(axis=0) # sum of each column

array([12, 15, 18, 21])

In [96]:
b.sum(axis=1) # sum of each row

array([ 6, 22, 38])

In [97]:
b.min(axis=0) # min in each axis

array([0, 1, 2, 3])

In [98]:
b.max(axis=1)

array([ 3,  7, 11])

In [99]:
b.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66])

In [100]:
b.cumsum(axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]])

In [101]:
b.cumprod(axis=0)

array([[  0,   1,   2,   3],
       [  0,   5,  12,  21],
       [  0,  45, 120, 231]])

In [102]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [103]:
a

array([[ 4,  8, 12],
       [16, 20, 24],
       [28, 32, 36]])

In [104]:
b = a*a

In [105]:
b

array([[  16,   64,  144],
       [ 256,  400,  576],
       [ 784, 1024, 1296]])

In [106]:
np.sqrt(b)

array([[ 4.,  8., 12.],
       [16., 20., 24.],
       [28., 32., 36.]])

In [107]:
np.add(a,a)

array([[ 8, 16, 24],
       [32, 40, 48],
       [56, 64, 72]])

In [108]:
a.mean()

20.0

In [109]:
a.mean(axis=0)

array([16., 20., 24.])

In [111]:
a = np.arange(10)*3

In [112]:
a

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [113]:
a[::-1]

array([27, 24, 21, 18, 15, 12,  9,  6,  3,  0])

In [114]:
a[:4:2] = 200

In [115]:
a

array([200,   3, 200,   9,  12,  15,  18,  21,  24,  27])

In [117]:
a**(1/7)

array([2.13166312, 1.16993081, 2.13166312, 1.36873811, 1.42616164,
       1.4723567 , 1.51120939, 1.54485766, 1.57461011, 1.60132889])

In [119]:
def func(x,y):
    return 10*x+y

np.fromfunction(func, (2,2))

array([[ 0.,  1.],
       [10., 11.]])

In [121]:
def func(x,y):
    return 10*x+y

np.fromfunction(func, (2,3))

array([[ 0.,  1.,  2.],
       [10., 11., 12.]])

In [122]:
help(np.fromfunction)

Help on function fromfunction in module numpy:

fromfunction(function, shape, **kwargs)
    Construct an array by executing a function over each coordinate.
    
    The resulting array therefore has a value ``fn(x, y, z)`` at
    coordinate ``(x, y, z)``.
    
    Parameters
    ----------
    function : callable
        The function is called with N parameters, where N is the rank of
        `shape`.  Each parameter represents the coordinates of the array
        varying along a specific axis.  For example, if `shape`
        were ``(2, 2)``, then the parameters would be
        ``array([[0, 0], [1, 1]])`` and ``array([[0, 1], [0, 1]])``
    shape : (N,) tuple of ints
        Shape of the output array, which also determines the shape of
        the coordinate arrays passed to `function`.
    dtype : data-type, optional
        Data-type of the coordinate arrays passed to `function`.
        By default, `dtype` is float.
    
    Returns
    -------
    fromfunction : any
        The 

In [123]:
b

array([[  16,   64,  144],
       [ 256,  400,  576],
       [ 784, 1024, 1296]])

In [124]:
b[:2]

array([[ 16,  64, 144],
       [256, 400, 576]])

In [125]:
b[0]

array([ 16,  64, 144])

In [126]:
b[:,1]

array([  64,  400, 1024])

In [129]:
b[0:3,1] # b01 b11 b21

array([  64,  400, 1024])

In [130]:
b[0,1]

64

In [132]:
b[1:3, :]

array([[ 256,  400,  576],
       [ 784, 1024, 1296]])

In [133]:
b[1,:]

array([256, 400, 576])

In [134]:
b[1:]

array([[ 256,  400,  576],
       [ 784, 1024, 1296]])

In [135]:
b[1:,1
]

array([ 400, 1024])

In [139]:
b[:,:]

array([[  16,   64,  144],
       [ 256,  400,  576],
       [ 784, 1024, 1296]])

In [140]:
b[-1]


array([ 784, 1024, 1296])

In [141]:
b[1,2]

576

In [143]:
b[1] [2]

576

In [147]:
b

array([[  16,   64,  144],
       [ 256,  400,  576],
       [ 784, 1024, 1296]])

In [148]:
b[1,:]

array([256, 400, 576])

In [149]:
b[1]

array([256, 400, 576])

In [150]:
b[1,...]

array([256, 400, 576])

In [155]:
b[-1]

array([ 784, 1024, 1296])

In [156]:
c = np.arange(12).reshape(2,2,3)

In [157]:
c

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [158]:
c.shape

(2, 2, 3)

In [159]:
c.ndim

3

In [163]:
c[1].ndim

2

In [164]:
c[1]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [165]:
c[1,...]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [167]:
c[1, 1]

array([ 9, 10, 11])

In [168]:
c[1,1,1]

10

In [169]:
c[:,1,1]

array([ 4, 10])

In [170]:
c

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [171]:
c.flat

In [172]:
list(c.flat)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [174]:
a = np.floor(10* np.random.random((2,3)))

In [175]:
a

array([[1., 4., 3.],
       [5., 5., 9.]])

In [177]:
a.shape

(2, 3)

In [182]:
a.ravel() # flattens and returns a numpy array

array([1., 4., 3., 5., 5., 9.])

In [183]:
a.reshape(3,2)

array([[1., 4.],
       [3., 5.],
       [5., 9.]])

In [184]:
a

array([[1., 4., 3.],
       [5., 5., 9.]])

In [185]:
a.T # transpose

array([[1., 5.],
       [4., 5.],
       [3., 9.]])

In [186]:
print(a.shape)
print(a.T.shape)
print(a.T.T.shape)

(2, 3)
(3, 2)
(2, 3)


In [187]:
a

array([[1., 4., 3.],
       [5., 5., 9.]])

In [188]:

a.resize((3,3))

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [192]:
a = np.arange(12).reshape(4,3)
# a.resize((3,4))

In [193]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [194]:
a.resize((3,4))

In [195]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [196]:
a.reshape(6,-1)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [197]:
a = np.floor(10*np.random.random((2,2)))

In [198]:
b = np.floor(10*np.random.random((2,2)))

In [199]:
a

array([[4., 4.],
       [5., 2.]])

In [200]:
b

array([[4., 9.],
       [5., 3.]])

In [201]:
np.vstack((a,b))

array([[4., 4.],
       [5., 2.],
       [4., 9.],
       [5., 3.]])

In [202]:
np.hstack((a,b))

array([[4., 4., 4., 9.],
       [5., 2., 5., 3.]])

In [206]:
from numpy import newaxis
np.column_stack((a,b))

array([[4., 4., 4., 9.],
       [5., 2., 5., 3.]])

In [207]:
a = np.array([1,3])

In [208]:
b = np.array([3,9])

In [210]:
np.hstack((a,b))

array([1, 3, 3, 9])

In [211]:
np.vstack((a,b))

array([[1, 3],
       [3, 9]])

In [212]:
np.vstack((a,b)).shape

(2, 2)

In [213]:
np.column_stack((a,b))

array([[1, 3],
       [3, 9]])

In [214]:
a

array([1, 3])

In [217]:
b = a[:,newaxis]

In [218]:
a.shape


(2,)

In [221]:
a.reshape(2,1)

array([[1],
       [3]])

In [222]:
a

array([1, 3])

In [219]:
b

array([[1],
       [3]])

In [220]:
b.shape

(2, 1)

In [223]:
a

array([1, 3])

In [224]:
b

array([[1],
       [3]])

In [226]:
np.column_stack((b,b))

array([[1, 1],
       [3, 3]])

In [227]:
np.column_stack((a,a))


array([[1, 1],
       [3, 3]])

In [228]:
np.vstack((a,a))

array([[1, 3],
       [1, 3]])

In [229]:
np.r_[1:4,0,4]

array([1, 2, 3, 0, 4])

In [230]:
np.array([1:4])

SyntaxError: invalid syntax (<ipython-input-230-70a69fd8a061>, line 1)

In [233]:
c= np.c_[1,4,5]

In [234]:
print(c)

[[1 4 5]]


In [235]:
c.shape

(1, 3)

In [249]:
a = a.reshape(1,2)

In [242]:
b = b.reshape(1,2)

In [243]:
b

array([[1, 3]])

In [251]:
np.concatenate((a,b))

array([[1, 3],
       [1, 3]])

In [250]:
print(a.shape)
print(b.shape)

(1, 2)
(1, 2)


In [252]:
a = np.arange(10).reshape(2,5)

In [254]:
b = np.arange(10,20).reshape(2,5)

In [255]:
np.concatenate((a,b))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### Splitting one array into several smaller ones¶

In [256]:
a = np.floor(10*np.random.random((2,12)))

In [257]:
a

array([[5., 4., 5., 7., 7., 2., 9., 9., 1., 8., 3., 4.],
       [4., 1., 8., 4., 9., 8., 8., 5., 9., 7., 3., 8.]])

In [258]:
np.hsplit(a, 3)

[array([[5., 4., 5., 7.],
        [4., 1., 8., 4.]]),
 array([[7., 2., 9., 9.],
        [9., 8., 8., 5.]]),
 array([[1., 8., 3., 4.],
        [9., 7., 3., 8.]])]

In [259]:
np.hsplit(a,4)

[array([[5., 4., 5.],
        [4., 1., 8.]]),
 array([[7., 7., 2.],
        [4., 9., 8.]]),
 array([[9., 9., 1.],
        [8., 5., 9.]]),
 array([[8., 3., 4.],
        [7., 3., 8.]])]

In [260]:
np.hsplit(a,5)

ValueError: array split does not result in an equal division

In [263]:
np.hsplit(a, (3,4)) # Split a after the third and the fourth column

[array([[5., 4., 5.],
        [4., 1., 8.]]),
 array([[7.],
        [4.]]),
 array([[7., 2., 9., 9., 1., 8., 3., 4.],
        [9., 8., 8., 5., 9., 7., 3., 8.]])]

In [264]:
a

array([[5., 4., 5., 7., 7., 2., 9., 9., 1., 8., 3., 4.],
       [4., 1., 8., 4., 9., 8., 8., 5., 9., 7., 3., 8.]])

In [269]:
np.vsplit(a.reshape(6,4), 2)

[array([[5., 4., 5., 7.],
        [7., 2., 9., 9.],
        [1., 8., 3., 4.]]),
 array([[4., 1., 8., 4.],
        [9., 8., 8., 5.],
        [9., 7., 3., 8.]])]

In [273]:
b = a.reshape(6,4)

In [275]:
np.vsplit(b, 3)

[array([[5., 4., 5., 7.],
        [7., 2., 9., 9.]]),
 array([[1., 8., 3., 4.],
        [4., 1., 8., 4.]]),
 array([[9., 8., 8., 5.],
        [9., 7., 3., 8.]])]

In [276]:
np.hsplit(a, (1,2))

[array([[5.],
        [4.]]),
 array([[4.],
        [1.]]),
 array([[5., 7., 7., 2., 9., 9., 1., 8., 3., 4.],
        [8., 4., 9., 8., 8., 5., 9., 7., 3., 8.]])]

In [277]:
a

array([[5., 4., 5., 7., 7., 2., 9., 9., 1., 8., 3., 4.],
       [4., 1., 8., 4., 9., 8., 8., 5., 9., 7., 3., 8.]])